kind: pipeline
name: default

workspace:
  base: /app
  path: .

steps:
- name: build
  image: node
  volumes:
  - name: cache
    path: /tmp/cache
  - name: apps
    path: /app
  commands:
  - npm install
  - npm run build
- name: test
  image: node
  volumes:
  - name: cache
    path: /tmp/cache
  - name: apps
    path: /app
  commands:
  - npm test

volumes:
- name: cache
  host:
    path: /var/lib/cache
- name: app
  host:
    path: /app
